trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'chrismith/chuck-norris-logs'
  dockerHub: 'dockerHub'

steps:
- task: Docker@2
  displayName: Build Chuck Norris Logs
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: Dockerfile
    tags: |
      latest
      1.0

- task: Docker@2
  displayName: Docker Login
  inputs: 
    command: login
    containerRegistry: $(dockerHub)

- task: Docker@2
  displayName: Push Chuck Norris Logs
  inputs:
    containerRegistry: $(dockerHub)
    repository: $(imageName)
    command: push
    tags: |
      latest
      1.0